### ISSUE TITLE
Columns misaligned

### ISSUE THREAD

**Issue by wd021** [iron-fish/block-explorer#104]
Transaction page columns misaligned

<img width="1302" alt="Screenshot 2022-09-01 at 12 26 05" src="https://user-images.githubusercontent.com/2752586/188077326-49375590-8517-443f-934e-993f2934ee57.png">
<img width="829" alt="Screenshot 2022-09-01 at 12 25 56" src="https://user-images.githubusercontent.com/2752586/188077333-fe15d9ae-b344-4bd6-b6b4-447a7517ed77.png">

**Comment by azhurauski-sc** [comment]
👍
