### ISSUE TITLE
Timestamp showing 24:00+

### ISSUE THREAD

**Issue by wd021** [iron-fish/block-explorer#116]
Block explorer showing 24:00:00UTC+ as current time
<img width="1770" alt="Screenshot 2022-09-25 at 07 27 02" src="https://user-images.githubusercontent.com/2752586/192131246-dcba8b0c-5556-43c2-a800-7351ade06034.png">

**Comment by dguenther** [comment]
I believe this should be fixed by #117, please reopen if not!
