### ISSUE TITLE
negative difficulty on block explorer

### ISSUE THREAD

**Issue by knight2008** [iron-fish/block-explorer#53]
negative difficulty on block explorer
Difficulty -1279419239

https://explorer.ironfish.network/#blocks
![20211208005028](https://user-images.githubusercontent.com/28775897/145071894-fb556e29-3694-4032-8809-846a9084e119.png)

**Comment by dguenther** [comment]
I moved this to the `block-explorer` repo since it's related to that UI.

Also, this should be fixed now.
