### ISSUE TITLE
0.1.11 the explorer  block height is 

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/block-explorer#62]
After upgrade to 0.1.11, the block height of the block-explorer is far behind the current height. 
By comparing the time, I found that the latest block time displayed by the browser is exactly 5 hours behind the current time.
5 hours just a function in latest upgrade,
[https://github.com/iron-fish/ironfish/pull/764](url)
 
I'm not sure if it's a coincidence or a bug with this pull.

**Comment by deekerno** [comment]
This was due to instability with the API, which has been solved in a number of ways.
