### ISSUE TITLE
Charts data 1 week behind

### ISSUE THREAD

**Issue by wd021** [iron-fish/block-explorer#81]
Seems like chart data stopped updating 1 week ago 👇 

<img width="800" alt="Screenshot 2022-05-31 at 08 23 38" src="https://user-images.githubusercontent.com/2752586/171116020-fe1c9712-4a57-4fc6-afea-1039b277db20.png">

**Comment by dangdennis** [comment]
Looks like it's no longer an issue.

**Comment by deekerno** [comment]
Charts are indeed up-to-date. Thanks for reporting!
