### ISSUE TITLE
404 page overflows

### ISSUE THREAD

**Issue by wd021** [iron-fish/block-explorer#88]
<img width="480" alt="Screen Shot 2022-08-07 at 1 26 01 PM" src="https://user-images.githubusercontent.com/2752586/183291281-e21e9c1b-4ce0-4712-bfd5-61e86053ffaf.png">
<img width="1661" alt="Screen Shot 2022-08-07 at 1 25 35 PM" src="https://user-images.githubusercontent.com/2752586/183291282-9a2f63ad-b682-4e40-aaca-63f87764b8b9.png">

**Comment by azhurauski-sc** [comment]
That is known issue fixing in progress.

**Comment by azhurauski-sc** [comment]
Fixed in https://github.com/iron-fish/block-explorer-v2/pull/87
